package: uuidify

generate:
  client: true
  types: true
  models: true

output: .
output-options:
  skip-fmt: false

templates:
  - type: client
    dir: templates
  - type: types
    dir: templates
  - type: parameters
    dir: templates
